### ISSUE TITLE
Readme images

### ISSUE THREAD

**Issue by grudus** [grudus/Snake#2]
![screenshot 2017-07-30](https://user-images.githubusercontent.com/18220458/28889943-e1982256-77c5-11e7-8600-92e2aecea7bb.png)

![screenshot 2017-08-02 1](https://user-images.githubusercontent.com/18220458/28890412-52e5455a-77c7-11e7-8e00-d70063d942ec.png)
![screenshot 2017-08-02 2](https://user-images.githubusercontent.com/18220458/28890414-52e8d472-77c7-11e7-9148-8c49cacb299f.png)
![screenshot 2017-08-02](https://user-images.githubusercontent.com/18220458/28890413-52e6437e-77c7-11e7-8478-8006450f209c.png)
![screenshot 2017-08-03](https://user-images.githubusercontent.com/18220458/28898896-7f091546-77e8-11e7-9076-d18a98d3fa4b.png)
![screenshot 2017-08-05 2](https://user-images.githubusercontent.com/18220458/28995509-306b8ebe-79eb-11e7-8743-372f5aa7a7d2.png)

**Comment by kubukoz** [comment]
najgorzej xDDDDDDDD
